language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev
  - mysql -e 'create database testia_test;'
rvm:
  - "1.9.3"
  - "2.1.1"
before_script:
  - bundle exec rake db:schema:load
script: bundle exec rake spec